config/routes.rb
Rails.application.routes.draw do

  root "artists#index"
  get "artists" => "artists#index"
  get 'show/new' => "artists#create", as: :new_song
  get "artists/:id" => "artists#show", as: :artist





# resources :artists , :songs

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def list
   @artists = Artist.all
  end

  def index
      @artists = Artist.all
    end

    def show
    @artist = Artist.find(params[:id])

    end


    def delete
    @artist = Artist.find(params[:id])

    @artist.destroy

    redirect_to :action => 'list'
  end

  def artist_params
      params.require(:artists).permit(:name)
   end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def new
     @song = Song.new

  end

  def list
   @songs = Song.all
  end

  def create
   @song = Song.new(song_params)

   if @song.save
      redirect_to :action => 'list'
    else

       render :action => 'new'

      end

  end

  def song_params
     params.require(:songs).permit(:name,:atrist_id)
  end

  def delete
   @song = Song.find(params[:id])

   @song.destroy

   redirect_to songs_path
  end

 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<h1>Artists</h1>

<% @artists.each do |artist| %>
  <p><%= artist.name %></p>
  <p><%= link_to artist.name, artist_path(artist.id) %></p>
<% end %>

app/views/artists/new.html.erb
<h1>new a Song</h1>


<%= form_tag :action => 'create' do %>
<p><label for = "song name">Song Name</label>:


<%= submit_tag "Create" %>

<% end -%>
<%= link_to 'Back', {:action => 'list'} %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>


<%= image_tag @artist.picture %>

<% @artist.songs.each do |song| %>
  <p><%= song.name %></p>

<% end %>

<%= link_to "[Delete]", artist_path(@artist.id), method: :delete, data: { confirm: "Are you sure?" } %>
<%= link_to "[Add Song]", new_song_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>